name: Unit Test

on:
  workflow_dispatch:
  push:

jobs:

  test_blind_accessory:
    name: Test BlindAccessory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Clear Previous Build
        run: pio run -t clean -e embeded_env
      - name: Build PlatformIO Project
        run: pio test -e embeded_env -f test_BlindAccessory --without-uploading --without-testing
      - name: Test Embeded
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 180000
          fail_text: FAILED
          scenario: 'senario.test.yaml'

  test_boiler_accessory:
    name: Test BoilerAccessory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Clear Previous Build
        run: pio run -t clean -e embeded_env
      - name: Build PlatformIO Project
        run: pio test -e embeded_env -f test_BoilerAccessory --without-uploading --without-testing
      - name: Test Embeded
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 180000
          fail_text: FAILED
          scenario: 'senario.test.yaml'