name: Unit Test

on:
  workflow_dispatch:
  push:

jobs:
  - Test-Blind:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio test -e embeded_env -f test_BlindAccessory --without-uploading --without-testing

      - name: Test Embeded
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 180000
          fail_text: FAILED
          scenario: 'senario.test.yaml'

  - Test-Boiler:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio test -e embeded_env -f test_BoilerAccessory --without-uploading --without-testing

      - name: Test Embeded
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 180000
          fail_text: FAILED
          scenario: 'senario.test.yaml'
          